import itertools
import string

def bruteforce_attack():
# This will be the function that will take the password generated by the randomizer and test it against the password file that needs to be cracked.

# Will most likely have system commands to interact with password protected file

def randomizer():
# This function will be responsible for generating unique passwords while
# keeping track so it doesnt repeat itself.

# This function must also be able to take parameters like the minimum password
# length and maximum password length

def wordlist():
# This function will be responsible for using password files and wordlists and
# testing them against password protected files

def main():
# initializes everything
